version: "3"
name: python3_workspace

services:
  python3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
