version: "3.8"
services:
  py_crawler:
    platform: linux/x86_64
    build:
      context: .
    volumes:
      - .:/app
      - py_crawler_venv:/app/.venv
    stdin_open: true
    tty: true
volumes:
  py_crawler_venv:

